### ISSUE TITLE
.maf file not produced ?

### ISSUE THREAD

**Issue by Manisha0328** [hsinnan75/GSAlign#12]
Hello,
First of all, thanks for this amazing fast genome alignment tool!

The program does not output .maf file for an alignment between two .fasta files. However, all other files are produced after alignment is done.
Attached screenshot shows some of the last lines of console output.
<img width="543" alt="Capture" src="https://user-images.githubusercontent.com/71558640/108602873-96788180-73ca-11eb-9d64-4605eaf6dc73.PNG">

Please help or comment if there is some mistake in using the tool efficiently.
I really need the .maf file. 
Many thanks in advance!

Command used:
.../GSAlign -t 4 -slen 20 -alen 2000 -i <indexfile> -q <inputfilename> -o <outputfilename> -fmt 1 -dp

**Comment by hsinnan75** [comment]
Hi! It looks like GSAlign could not find alignments between the two sequences. You may use different parameters to lower the thresholds and try again. Since your sequences are not very long, I'll suggest to use -slen 15 -alen 100 or -sen (sensitive mode). If there should be alignments and GSAlign could not detect them, please let me know. Thank you!
